### PR TITLE
Adding my country and the capital city.

### PR DESCRIPTION
**Pull request by txd481**
Hope I'm doing it the right way. xD

### CODE REVIEW

**Comment by nikeshashar** [comment]
That's the one! Awesome work :). Are you learning to code?

**Comment by txd481** [comment]
Yes I am. Actually I started while ago but now I am learning github :D :)

2016-03-12 21:20 GMT+00:00 Nikesh Ashar notifications@github.com:

> Closed #575 https://github.com/makersacademy/the-cat/pull/575.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/makersacademy/the-cat/pull/575#event-587539612.

## 

Tanya Daskova

BSc Computer Science
The University of Birmingham

**Comment by txd481** [comment]
Oh but why I still can't see the folder in the remote repo?

2016-03-12 21:28 GMT+00:00 Tanya Daskova tanyadaskova@gmail.com:

> Yes I am. Actually I started while ago but now I am learning github :D :)
> 
> 2016-03-12 21:20 GMT+00:00 Nikesh Ashar notifications@github.com:
> 
> > Closed #575 https://github.com/makersacademy/the-cat/pull/575.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/makersacademy/the-cat/pull/575#event-587539612.
> 
> ## 
> 
> Tanya Daskova
> 
> BSc Computer Science
> The University of Birmingham

## 

Tanya Daskova

BSc Computer Science
The University of Birmingham

**Comment by nikeshashar** [comment]
We don't usually merge them in to the repo - as it's part of an exercise for our student's who are learning with us.

**Comment by nikeshashar** [comment]
Have you tried this : https://github.com/makersacademy/unixoid-challenge ?

**Comment by txd481** [comment]
Ohhh, Okay!

Apologies, didn't know that.

I will have a look into the link you sent me.

Thank you Nikesh!

2016-03-12 22:49 GMT+00:00 Nikesh Ashar notifications@github.com:

> Have you tried this : https://github.com/makersacademy/unixoid-challenge ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/makersacademy/the-cat/pull/575#issuecomment-195821393
> .

## 

Tanya Daskova

BSc Computer Science
The University of Birmingham

**Pull request closed without merging**
